<?php
require_once 'db.php';
global $PDO;
session_start();
$name = $_POST['name'];
$id   = intval( $_POST['id'] );

if ( $id ) {
	// updates data in db
	try {
		$query     = 'UPDATE persons SET name = :name WHERE id = :id';
		$statement = $PDO->prepare( $query );
		$statement->execute( array(
			"id"   => $id,
			"name" => $name
		) );
		$_SESSION['info'] = "Person data has been updated ($name).";
	} catch ( PDOException $e ) {
		$_SESSION['error'] = 'Query error: ' . $e->getMessage();
		header( 'Location: ../create-edit.php?error=1' );
		die();
	}
} else {
	// save new in db
	try {
		// we omit inserting value for 'id' column here because it is an autogenerated primary key column
		$query     = 'INSERT INTO persons(name) VALUES(?)';
		$statement = $PDO->prepare( $query );
		$statement->execute( array( $name ) );
		$_SESSION['info'] = "New person data has been saved ($name).";
	} catch ( PDOException $e ) {
		$_SESSION['error'] = 'Query error: ' . $e->getMessage();
		header( 'Location: ../create-edit.php?error=1' );
		die();
	}
}

header( 'Location: ../index.php' );
die();